### PR TITLE
fixed issue where auto created admin accout was not an admin account

### LINKED ISSUE #11: ensureAdminAccount: User isn't declared as Admin
Server crashed on second start, trying to create an admin. Mail already exists so it couldn't create a new admin. User already exists but couldn't be found because it isn't declared as admin.

### PR DESCRIPTION
**Pull request by ProgramPhoenix**
fixing issue #11

### CODE REVIEW

File: backend/controller/AccountController.ts [hunk 1]
```diff
@@ -135,16 +135,19 @@ export class AccountController {
...
         const user = await DBUser.findOneBy({ type: UserClass.ADMIN });
         if (user === null) {
-            const adminUser: Partial<IUser> = {};
+            const adminUser = new DBUser();
+            adminUser.type = UserClass.ADMIN;
             adminUser.name = 'admin';
             adminUser.mail = 'admin@loernwerk.de';
             const pw = crypto.randomBytes(16).toString('hex');
             console.log(
                 'Admin account created, username: admin, mail: admin@loernwerk.de, password: ' +
```
Comment (Kr0nox) [inline backend/controller/AccountController.ts]: Could we insert username and email from the DBUser?

Comment (ProgramPhoenix) [reply backend/controller/AccountController.ts]: you mean from a config file?

Comment (c0derMo) [reply backend/controller/AccountController.ts]: I assume he means replacing them inside the `console.log` instead of hardcoding them - might be an idea, so you could change it in one place instead of having two places - I'd also put the logging message below the saving, so if the log message gets printed, the account has already been created, which is currently indicated by the message

Comment (Kr0nox) [reply backend/controller/AccountController.ts]: Yes, ment that

Comment (ProgramPhoenix) [reply backend/controller/AccountController.ts]: done

**Review by c0derMo — APPROVED** [review]

File: backend/controller/AccountController.ts (hunk 1 above)
Comment (Kr0nox) [reply backend/controller/AccountController.ts]: Do we want to leave this as concatination or convert to the insertion method used in most other strings in the project

Comment (ProgramPhoenix) [reply backend/controller/AccountController.ts]: you mean like this example: `var s = "hello ${my_name}, how are you doing";`?

Comment (Kr0nox) [reply backend/controller/AccountController.ts]: yes

Comment (c0derMo) [reply backend/controller/AccountController.ts]: I'd say so, but with backticks ` instead of " like
```js
console.log(`something${someVariable}`)
```
since that's how JS does it

Comment (ProgramPhoenix) [reply backend/controller/AccountController.ts]: kk

Comment (ProgramPhoenix) [reply backend/controller/AccountController.ts]: alright done

**Review by Kr0nox — APPROVED** [review]
