### PR TITLE
Frontend/admin view

### LINKED ISSUE #19: Backend server dosent returns an error in API, after user deletes and requests himself. Backend error is not catched
How to reproduce:

1. login
2. move to localhost:5173/account
3. delete Account
4. reload website

Backenderror:
>[dev:backend] ...\loernwerk\backend\controller\AccountController.ts:103
>[dev:backend]             throw new LoernwerkError(
>[dev:backend]                   ^
>[dev:backend] LoernwerkError: No existing User with given ID
>[dev:backend]     at Function.getAccountById (C:\Users\david\Desktop\loernwerk\backend\controlle\AccountController.ts:103:19)
>[dev:backend]     at async C:\Users\david\Desktop\loernwerk\backend\router\AccountRouterFactory.ts:110:26 {
>[dev:backend]   code: 'NOT_FOUND'
>[dev:backend] }
>[dev:backend] npm run dev:backend exited with code 1`

this error will not normaly occur in the account view, as long users can not delete themselves. but this error will probably occur in the admin view, after an admin deletes an account. (Depends on implementation)

### PR DESCRIPTION
**Pull request by ProgramPhoenix**
This is a draft request since some things are still missing (or todo), but i do not claim completeness:
- [x] create account does not refresh the list (dont know why) Update: I put the refresh at the wrong container 😂 
- [x] may some further styling (?)
- [x] the buttons for the sequences (show, delete) are not working now
- [x] removing the sequence test object
- [x] better (more?) doc (?) (just report it)
- [x] the account view is not working anymore? 🤮 Update: fixed ambigous router, but still not working Update2: Hmm the error is shown if you are not logged in, but as soon as you are logged in, the account view isnt working anymore. why?
- [x] the admin bypass isn't working? Update: we checked the username for correct password length 😂 Update2: Our valid checks were also a bit wrong.
- [x] the scrollcontainer, when the users are not fitting on the page, exists, but is larger than the site and i dont know why

Edit: more checks
Edit: even more checks

### CODE REVIEW

**Comment by ProgramPhoenix** [comment]
i just noticed that the changes at the account controller may fix issue #19, i will test it a bit

Edit: Since the account view seems not to work on this branch i can't test it for now

**Comment by c0derMo** [comment]
I may have found a fix for the account list not updating properly when users are added / deleted (not sure if that's still an issue)

Instead of casting the prop to a ref inside the account list and using a watcher, which doesn't work if array-elements are added/removed, bind the view to the prop directly (`v-for="user in props.accounts"`) and use a computed property for the filtering

**Comment by c0derMo** [comment]
I also figured out why the accountview isn't working anymore - the backend never replies to the request, since it tries to find the user with the id `undefined` - the check in AccountRouterFactory line 115 needs to be changed to `reqUserId !== undefined`

**Comment by ProgramPhoenix** [comment]
Since everything should work now, i marked this pr as ready for review

File: frontend/src/components/AccountCreationContainer.vue [hunk 1]
```diff
@@ -0,0 +1,129 @@
+<template>
```
Comment (Kr0nox) [inline frontend/src/components/AccountCreationContainer.vue:1]: Maybe we could look into combining some code of this and the EditContainer

File: frontend/src/components/AccountList.vue [hunk 2]
```diff
@@ -0,0 +1,51 @@
+<template>
+  <div class="flex flex-col">
```
Comment (Kr0nox) [inline frontend/src/components/AccountList.vue]: I think it would be better, if this was the container directly. then the search bar and create account button could be moved into that header. this would ensure a better user experience, since these options are always available and not only when scolled all the way up

File: frontend/src/components/AccountCreationContainer.vue [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+  </div>
+</template>
+<script setup lang="ts">
+import { ref } from 'vue';
+import TextInputComponent from './TextInputComponent.vue';
+import ButtonComponent from './ButtonComponent.vue';
+import ContainerComponent from './ContainerComponent.vue';
+import { AccountRestInterface } from '../restInterfaces/AccountRestInterface';
+
+const emit = defineEmits(['create']);
```
Comment (Kr0nox) [inline frontend/src/components/AccountCreationContainer.vue]: doc of emit

File: frontend/src/components/AccountList.vue [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+   * emits, when the user clicks on a user in the list
+   * @param userId the userId of the user clicked on
+   */
+  'selected',
+]);
+
+const filterText = ref('');
+const filteredAccountList = computed(() => {
+  return props.accounts?.filter((element) => {
+    return element.name?.match(filterText.value.concat('.*'));
```
Comment (Kr0nox) [inline frontend/src/components/AccountList.vue]: i think `element.name?.includes(filterText.value)` would be a better filter

**Review by Kr0nox — CHANGES_REQUESTED** [review]

File: frontend/src/components/AccountList.vue (hunk 4 above)
Comment (ProgramPhoenix) [reply frontend/src/components/AccountList.vue]: i don't see any difference, but then i guess i'll remove the `.concat('.*')`

File: frontend/src/components/AccountList.vue (hunk 2 above)
Comment (ProgramPhoenix) [reply frontend/src/components/AccountList.vue]: you mean like this?

File: frontend/src/components/AccountCreationContainer.vue (hunk 1 above)
Comment (ProgramPhoenix) [reply frontend/src/components/AccountCreationContainer.vue:1]: we could may capsule the html code again, i dont see, where we could capsule the ts code.

File: backend/router/AccountRouterFactory.ts [hunk 5]
```diff
@@ -44,14 +44,15 @@ export class AccountRouterFactory extends RouterFactory {
...
+            requireBody('name', 'mail', 'password'),
             async (req, res) => {
                 try {
                     const user = await AccountController.createNewAccount(
                         req.body
                     );
                     res.status(201).json({ id: user.id });
-                } catch {
+                } catch (e) {
+                    console.log(e.message);
```
Comment (c0derMo) [inline backend/router/AccountRouterFactory.ts]: console.log

File: backend/router/AccountRouterFactory.ts [hunk 6]
```diff
@@ -101,17 +102,30 @@ export class AccountRouterFactory extends RouterFactory {
                 try {
                     await AccountController.deleteAccount(req.body.id);
                     res.sendStatus(204);
-                } catch {
+                } catch (e) {
+                    console.log(e.message);
```
Comment (c0derMo) [inline backend/router/AccountRouterFactory.ts]: console.log

File: backend/router/AccountRouterFactory.ts [hunk 7]
```diff
@@ -120,6 +134,13 @@ export class AccountRouterFactory extends RouterFactory {
             });
         });
 
+        accountRouter.get('/list', requireAdmin, async (req, res) => {
+            const listUsers = await AccountController.getAllAccounts();
+            res.status(200).json(listUsers);
+        });
+
+        return accountRouter;
```
Comment (c0derMo) [inline backend/router/AccountRouterFactory.ts]: This return should probably be at the end of the function

File: frontend/src/components/AccountCreationContainer.vue [hunk 8]
```diff
@@ -0,0 +1,134 @@
...
+  }
+
+  try {
+    await AccountRestInterface.addAccount({
+      name: nameField.value,
+      mail: mailField.value,
+      password: pwField.value,
+    });
+    displaySuccess.value = true;
+    console.log('create');
```
Comment (c0derMo) [inline frontend/src/components/AccountCreationContainer.vue]: log

File: frontend/src/components/AccountCreationContainer.vue [hunk 9]
```diff
@@ -0,0 +1,134 @@
...
+    emit('create');
+  } catch (e) {
+    console.log('server fault');
```
Comment (c0derMo) [inline frontend/src/components/AccountCreationContainer.vue]: log

File: frontend/src/components/AccountSequenceContainer.vue [hunk 10]
```diff
@@ -0,0 +1,66 @@
...
+    </template>
+    <div v-for="sequence in sequences" :key="sequence.code">
+      <ContainerComponent>
+        <div class="flex flex-col">
+          <div>
+            {{ sequence.name }}
+          </div>
+          <div class="flex">
+            <ButtonComponent @click="showSequence(sequence.code)">
+              anzeigen
```
Comment (c0derMo) [inline frontend/src/components/AccountSequenceContainer.vue]: Capitalize the button labels?

File: frontend/src/components/AccountSequenceContainer.vue [hunk 11]
```diff
@@ -0,0 +1,66 @@
...
+            </ButtonComponent>
+            <div class="flex-grow text-red-500">
+              <div v-if="showError">Löschen fehlgeschlagen</div>
+            </div>
+            <ButtonComponent @click="deleteSequence(sequence.code)">
+              löschen
```
Comment (c0derMo) [inline frontend/src/components/AccountSequenceContainer.vue]: Capitalize the button labels?

File: frontend/src/views/AdminView.vue [hunk 12]
```diff
@@ -0,0 +1,95 @@
...
+  accounts.value = await AccountRestInterface.getAccountMetaDataList();
+} catch (e) {
+  router.push('/');
+}
+/**
+ * Requests the user with the given id from the backend (currently not)
+ * @param id the id of the user
+ */
+async function updateUser(id: number): Promise<void> {
+  selectedUser.value = null;
```
Comment (c0derMo) [inline frontend/src/views/AdminView.vue]: Better solution to this, see dms

File: frontend/src/components/AccountCreationContainer.vue (hunk 1 above)
Comment (c0derMo) [reply frontend/src/components/AccountCreationContainer.vue:1]: We could distinguish inside the EditContainer if the supplied user is null or not, and if it is null, we have the "create" button, if it's not null, we have the "save" and "delete" button

**Review by c0derMo — CHANGES_REQUESTED** [review]

File: frontend/src/components/AccountList.vue (hunk 2 above)
Comment (Kr0nox) [reply frontend/src/components/AccountList.vue]: is my github bugged or are there no changes here?

Comment (ProgramPhoenix) [reply frontend/src/components/AccountList.vue]: if you press on this comment you get the code, when you commented i think. you have to press on files at the top

Comment (Kr0nox) [reply frontend/src/components/AccountList.vue]: I see what you changed. I meant having the Account List like this:
```Vue
<template>
  <ContainerComponent>
    <template #Header>
      <div class=flex>
        <!-- SeachBar and Add Button -->
      </div>
    </template>
    <template #default>
      <!-- List -->
    </template>
  </ContainerComponent>
</template>
```

File: frontend/src/components/AccountCreationContainer.vue (hunk 1 above)
Comment (c0derMo) [reply frontend/src/components/AccountCreationContainer.vue:1]: Although for the sake of getting this done and merged, I'd probably leave them seperated for now

File: frontend/src/components/AccountList.vue [hunk 13]
```diff
@@ -0,0 +1,50 @@
...
+
+<script setup lang="ts">
+import { PropType, computed, ref } from 'vue';
+import { IUser } from '../../../model/user/IUser';
+import ButtonComponent from './ButtonComponent.vue';
+import SearchBarComponent from './SearchBarComponent.vue';
+
+const props = defineProps({
+  accounts: {
+    type: Object as PropType<Partial<IUser>[]>,
```
Comment (Kr0nox) [inline frontend/src/components/AccountList.vue]: Use `Array<Partial<IUser>>` as type here

File: frontend/src/components/AccountSequenceContainer.vue [hunk 14]
```diff
@@ -0,0 +1,66 @@
...
+import { PropType, ref } from 'vue';
+import { ISequence } from '../../../model/sequence/ISequence';
+import ContainerComponent from './ContainerComponent.vue';
+import ButtonComponent from './ButtonComponent.vue';
+import { SequenceRestInterface } from '../restInterfaces/SequenceRestInterface';
+import { router } from '../router';
+
+defineProps({
+  sequences: {
+    type: Object as PropType<Array<ISequence>>,
```
Comment (Kr0nox) [inline frontend/src/components/AccountSequenceContainer.vue]: Use `Array<ISequence>` as type here

**Review by Kr0nox — CHANGES_REQUESTED** [review]

File: frontend/src/components/AccountList.vue (hunk 2 above)
Comment (ProgramPhoenix) [reply frontend/src/components/AccountList.vue]: should the add button really be in the accountlist? without we could may reuse it (i know we dont).  We could may just stick the addbutton at the bottom?

File: frontend/src/components/AccountSequenceContainer.vue (hunk 14 above)
Comment (ProgramPhoenix) [reply frontend/src/components/AccountSequenceContainer.vue]: i would change it to `ISequence[]` and keep the other, to be consistent with the model

File: frontend/src/components/AccountList.vue (hunk 2 above)
Comment (Kr0nox) [reply frontend/src/components/AccountList.vue]: From a sementic point of view it belongs into the container, like you already have it. and for the sake of user experience, the search bar and add button should both be in the header. So the other option would be to pull be search bar out and give the account list either an already filtered list or the string to filter by

Comment (ProgramPhoenix) [reply frontend/src/components/AccountList.vue]: hm the searchbar and the createbutton are no longer visible now. you could may look why?

File: frontend/src/components/AccountSequenceContainer.vue (hunk 14 above)
Comment (Kr0nox) [reply frontend/src/components/AccountSequenceContainer.vue]: The correct way to type arrays in vue is directly setting the type to array, without proptype. So just `type: Array<...>`

Comment (ProgramPhoenix) [reply frontend/src/components/AccountSequenceContainer.vue]: ah okay then i will go for it

File: frontend/src/components/AccountList.vue (hunk 2 above)
Comment (Kr0nox) [reply frontend/src/components/AccountList.vue]: In der accountList fehlt der import von der ContainerComponent

Comment (ProgramPhoenix) [reply frontend/src/components/AccountList.vue]: should work now

**Review by Kr0nox — APPROVED** [review]

**Review by c0derMo — APPROVED** [review]
